### ISSUE TITLE
This extension prevents the use of App Store Connect of Apple.

### ISSUE THREAD

**Issue by HanbitGaram** [Baw-Appie/SafeTransaction#5]
Hello, creator of the Chrome extension! I am someone who is using this program well. While analyzing the cause of some sites not being displayed properly, I found out that this plugin removes some of the contents of certain sites.

This extension prevents the page below from working.
1) https://appstoreconnect.apple.com/apps
2) https://appstoreconnect.apple.com/access/users
3) https://stella.place or https://misskey.io (Miskey-based sites such as etc. are not accessible)

I am aware that this is a burdensome bug. 
However, since many people use it, I believe that improvement is necessary.

**Comment by Baw-Appie** [comment]
개발자는 이러한 문제를 알고 있으며, 18개월 이내 수정됩니다.

**Comment by HanbitGaram** [comment]
According to what you said, does it mean that the problem will be resolved within a short time of 18 months?

I will continue to use this extension until you solve the problem.
If there is a problematic site, I will remove the extension and use the site. 

Thank you.
