### ISSUE TITLE
The IPInside bypass feature is disabled on the GukseChongHometax(NTS) site.

### ISSUE THREAD

**Issue by HanbitGaram** [Baw-Appie/SafeTransaction#6]
It seems to me that the competitor bypassed the extension to prevent it from working.
If you don't solve this problem quickly, you'll be bald, too.

**Comment by HanbitGaram** [comment]
I edited /etc/hosts,
104.21.6.32 ipinside-emulator.appie.dev

**Comment by Baw-Appie** [comment]
이 문제는 KT, SKT, LG U+의 DNS에서 개발자의 서버가 차단되어 발생하는 일이며, 개발자는 이러한 문제를 알고 있습니다.  
곧 이 문제를 해결한 업데이트가 제공될 것입니다.

**Comment by HanbitGaram** [comment]
Holy... ah.. ok.. U just stay.
Waiting... I will request PR

**Comment by Baw-Appie** [comment]
#7 에서 문제 해결이 진행되고 있습니다.

**Comment by Baw-Appie** [comment]
문제를 해결할 수 있을 만한 효과적인 방법이 아직까지 제시되지 않았습니다.  
이 문제를 해결하기 위하여 개발자는 곧 서버의 도메인을 변경할 예정입니다.  
추가적으로 서버의 코드를 오픈하는 것을 고려하고 있습니다..

**Comment by HanbitGaram** [comment]
Since the issue has been resolved, I will close the PR.
